name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad63a7ce8277fb3c6af3a027669f21bf58e692f7fe8772685dde85826ff65d57"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
