name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91919ce99f7a6b154c9ef0a47c69f846560765552d4760c059cb1eea9a54b715"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
