name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54ff377503835df6206c6b39ae9837566e72f64391343acd5d9dbd34dfa2ebe5"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
