name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "815dee97509d9e44c192fb48e36695636c350efa9202c376dc7f1d12a253ea2d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
