name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcf3bb68f2a5b793d122d739ebc78ff5d373066ead7f29f234b7d0a98aff818a"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
