name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a8a20d527b7994dfa75c261d7174d8209604319da579b4259c268c34633fab1"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
