name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36fff07d99fd1ded3acd3fe0c1604bf39cf2c681a79e387cbb5a18519a093889"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
