name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2b56139b16082c14831abbadf81606841c92b110b1527a3b9b754433ef27d72"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
