name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a8ce367af2e68b616d3b1a3f230743cf64385f2c1c2018ab71dbf383e69eac0"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
