name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c3f1727eb966a9392e971c8e89e97aa9b008813bd3de2cc8072ccd709d302ce"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
