name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0beb77448145149a6b34ee56e9a7de9cd5d22037e169cc8d2f19edb8138e84ea"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
