name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f343205e56d888958cbf24e55f311fcfb336003480fe17d215bfe689882ad3d5"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
