name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de57e8af448a949b9b14f2e3f2ce5d69633413884d7e65691cf106c46827d4ba"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
