name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb752e89d39c32e2e2499763fd1a8c645fe4604c87f00d4c6782cac6805cc0f1"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
