name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "645d011f334b5145a502cfa17b01dd68e452d6c67a8c9b7d02018191eb8d1303"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
