name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09bb3c209e2c9b62be3e4f9516a80277aad1e8059b9664dae7c41424d715c672"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
