name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c7c418a48f94c903fe050e4ae18dad44eca5d13819492496955cc4c990a558d"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
