name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "233660619d17b777f7c14f8466f09121f487dc1c53035bb1fbe1b4a8a50f7ddd"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
