name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9605a42b1593ccf62cb596e4886c2445b6b7143151c98c3016022cf26cf49796"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
