name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7466feebed2dc6b36b1dc8cff4906a84fdb8d8d71482047b4b15d4a86b222f52"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
