name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ecce020989623a9a5a464b8d82c0bbfd0e076050637eec23fd5ed42b365672a"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
