name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f1c768280e61c29660d2c6bd833d233a0b92bffdc5401c64de7cd4377645896"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
