name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dcf4328b078d14187eb0a0453b22374388d9c34e46e78c021b88bbbfd068e2c"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
