name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d995e3b23b046a02eb21106ef42788fabb38df80dbe11e11c628e448dee3d21e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
