name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a4c94f55de2dfc7e41a2a6f6dde6651351cb3ca0c4865fc98e4ff1aed16400b"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
