name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca47a61a2ff29993e1b2c0dc8a394ed5c6b4bdff907d2325daf97320a3b7f5ee"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
