name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42660a331ff642ef3ceb24967a4b1c61b066c5a66cf1db1ebda96e17159a8e05"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
