name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b54fb1bbc369e131985bb73073d25d501681f6bb416fb7dc8dea30a8a38a3c5"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
