name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a375409479fc568dc381d07db5d002d1fe4bcfc08c4f2d67cd667e3c3aade84"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
