name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2bd14d4deee0249c770d6e6988268f664f245094ed6fb3856b93995b9e3dd10"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
