name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d37b426f8bbb56ebfb535e04e2da3124e2abb37415701f1584aa0a6137b11ce"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
