name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fd21c58d53f86ed10190523681547abda786a990b81afe5fb50dba367bca6d3"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
