name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2e1af55a0e9f9aa2f07c3313d9c01bfd963d881d72d947fb769863ee3a560e4"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
