name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3c62fc9e7fa8b5afcf8f21e0a150c30c70068ca7858afc5a1d422e06debe7a7"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
