name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f41164df1efe717e6f8a0709c2964d86ee67d4f93a6ae43ed921ae91bf5dd1f6"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
