name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff0d1ffecd873a4054ed31d216fc9d79832097e83c63562d1d04c57d377fe492"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
