name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "175130ccf840f75b7b00f3018e559b0338561d311f625973548616885964bb9b"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
