name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87e6e8a89c0d9465be7403862dfe5be529d2c860a10e199a88c617c548fbe4eb"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
