name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcec5936da19040e0d5178eedc43555d1a7b72ecdddcfe86713afe4a75a171ec"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
