name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41d5406eca83e5dab380e13416a7896d4c2b3b66884ddb7cd7ce8c30ffc15677"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"

[options]
datapack-folder = "global_packs/required_data"
