name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38a40db0d06dce458103f7b102a6d2b70f08b06ec5cc8d22dd33d4ffac737f7c"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
