name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ec4f063aa9c89f356616993b6e9747afebfddc99b4abe252b26ff0c97bbc4b9"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
