name = "Minecolonies LT"
author = "SCBionicle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d8612842569568f86836cb24826f162bc9f6dcba6c676b56a7123506a7eec36"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
